-- TIER-1 #1 — NEPSE corporate-action awareness (bonus/rights/split/dividend).
-- Additive + idempotent — safe to re-run; mirrors 20260730000000_add_exchange.sql.
--
-- WHY: on a NEPSE ex-date the price drops MECHANICALLY (bonus/rights/dividend). The
-- spot-price outcome resolver would otherwise record a FALSE LOSS, and the
-- plausibility guard (marketData.sanityCheck) would REJECT the legit post-ex quote.
-- Both corrupt outcomes → weights → knowledge → the public track record.
--
-- corporate_actions is GLOBAL market data (like scans/signals/weights): NO user_id,
-- public-read + service-role write. Ex-dates + ratios are GROUND TRUTH — never
-- LLM-sourced (a wrong ex-date is financial harm), scraped deterministically.
--
-- Until this migration is applied, every CA read/write is gated behind schema-flag
-- probes (src/lib/schemaFlags.js) so an unmigrated DB behaves byte-for-byte as today.

-- ---- 1. Global corporate-actions table -------------------------------------
create table if not exists corporate_actions (
  id                bigint generated by default as identity primary key,
  symbol            text not null,
  exchange          text not null default 'NEPSE',
  action_type       text not null,            -- BONUS | RIGHTS | SPLIT | STOCK_DIV | CASH_DIV
  bonus_pct         numeric,                  -- % bonus share (BONUS/STOCK_DIV)
  dividend_pct      numeric,                  -- % cash dividend on par (CASH_DIV)
  rights_ratio      text,                     -- e.g. "10:1" (base:new) — RIGHTS
  rights_price      numeric,                  -- rights subscription price (rarely published)
  factor            numeric,                  -- multiplicative price adjustment (null = uncomputable → suppress)
  deduction         numeric,                  -- additive per-share deduction (cash dividend)
  ex_date           date,                     -- explicit ex-date when known
  book_closure_date date,                     -- merolagani publishes THIS, not always an ex-date
  source            text,                     -- provenance (e.g. 'merolagani')
  raw               jsonb,                    -- raw parsed fields for audit
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

-- Upsert key: one row per (symbol, exchange, action_type, book_closure_date). A
-- single announcement carrying both a cash dividend AND a bonus becomes TWO rows
-- (different action_type), which this unique index allows.
create unique index if not exists corporate_actions_uidx
  on corporate_actions (symbol, exchange, action_type, book_closure_date);
create index if not exists corporate_actions_symbol_ex_date_idx
  on corporate_actions (symbol, exchange, ex_date);

-- ---- 2. Signal adjustment columns (idempotent originals + cumulative factors) --
-- Immutable originals let outcome resolution RECOMPUTE the adjusted target/sl from
-- the CA data each run (no applied-flag): adjusted = orig * ca_factor - ca_deduction.
alter table signals add column if not exists orig_target  numeric;
alter table signals add column if not exists orig_sl      numeric;
alter table signals add column if not exists orig_price   numeric;
alter table signals add column if not exists ca_factor    numeric default 1;
alter table signals add column if not exists ca_deduction numeric default 0;
alter table signals add column if not exists ca_note      text;

-- ---- 3. RLS: public read, service-only write (mirrors 20260805130000_rls_on.sql) --
alter table corporate_actions enable row level security;
drop policy if exists public_read_corporate_actions on corporate_actions;
create policy public_read_corporate_actions on corporate_actions for select using (true);
-- (no write policy => only the service role, which bypasses RLS, can write)

-- NOTE: outcome='VOID' (terminal escape for a suppressed-too-long signal) needs NO
-- schema change — `outcome` is a free-text column.
