-- GLOBAL system/seed watchlist — the curated universe scanned for EVERYONE.
-- Additive + idempotent — safe to re-run; mirrors 20260806130000_corporate_actions.sql.
--
-- WHY: under multi-tenancy the scan universe is the UNION of every user's per-user
-- `watchlists` + discovery. When no user has added a symbol and discovery is empty,
-- the scan is STARVED (the UAT "Watch empty" bug). It also leaves signed-out/new
-- users with a blank Watch tab and no curated starting point. This table is a SINGLE
-- GLOBAL list (NO user_id) that seeds the scan union and serves the beginner
-- "curated watchlist" need, and it is the target of reinstated auto-promotion.
--
-- system_watchlist is GLOBAL market data (like corporate_actions/scans/signals): NO
-- user_id, public-read + service-role write. It stores SYMBOLS ONLY — never prices
-- (prices stay ground truth via the verified layer). Auto-promotion writes rows here
-- (source='discovery'), liquidity-filtered at write time.
--
-- Until this migration is applied, every read/write is gated behind a schema-flag
-- probe (src/lib/schemaFlags.js systemWatchlistReady) so an unmigrated DB behaves
-- byte-for-byte as today (scan union = user watchlists + discovery only, blank Watch
-- curated section, no promotion).

-- ---- 1. Global system watchlist table --------------------------------------
create table if not exists system_watchlist (
  id         bigint generated by default as identity primary key,
  symbol     text not null,
  exchange   text not null default 'NEPSE',
  source     text not null default 'seed',   -- seed | admin | discovery
  reason     text,
  active     boolean not null default true,
  added_at   timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- One row per (exchange, symbol). Upserts key on this; the seed INSERT below
-- ON CONFLICT DO NOTHING never clobbers an admin deactivation.
create unique index if not exists system_watchlist_uidx
  on system_watchlist (exchange, symbol);

-- ---- 2. Seed the curated NEPSE universe ------------------------------------
-- Idempotent: DO NOTHING on conflict so re-running never resurrects a symbol the
-- admin later deactivated (active is left untouched for existing rows).
insert into system_watchlist (symbol, exchange, source) values
  ('NABIL','NEPSE','seed'),
  ('NICA','NEPSE','seed'),
  ('HBL','NEPSE','seed'),
  ('ADBL','NEPSE','seed'),
  ('EBL','NEPSE','seed'),
  ('SCB','NEPSE','seed'),
  ('NIFRA','NEPSE','seed'),
  ('UPPER','NEPSE','seed'),
  ('CHCL','NEPSE','seed'),
  ('SHIVM','NEPSE','seed')
on conflict (exchange, symbol) do nothing;

-- ---- 3. RLS: public read, service-only write (mirrors corporate_actions) ----
alter table system_watchlist enable row level security;
drop policy if exists public_read_system_watchlist on system_watchlist;
create policy public_read_system_watchlist on system_watchlist for select using (true);
-- (no write policy => only the service role, which bypasses RLS, can write)
